### DISCUSSION TITLE
Extend remote_write config with X-Scope-OrgID

### DISCUSSION THREAD

**Discussion by till** [grafana-cold-storage/agent#1403] [Q&A] [answered]
I am looking for a mechanism to extend the `remote_write` configuration of the agent and add a custom header (for `X-Scope-OrgID`) based on source label. Similar to promtail where I can configure it to split logs based on labels (into different tenants) and send the header along to Loki. Couldn't find anything in the documentation, but maybe someone has an idea.

**Comment by rfratto** [comment, marked as answer]
Hi! The remote_write for metrics and traces support adding custom headers. 

Metrics example:

```yaml
metrics:
  configs:
  - name: example
    remote_write:
    - url: http://example.com
      headers:
        X-Scope-OrgID: example-org-id
```

Traces example:

```yaml
traces:
  configs:
  - name: example
    remote_write:
    - endpoint: example.com:443
      headers:
        X-Scope-OrgID: example-org-id
```
