### DISCUSSION TITLE
How to add service labels?

### DISCUSSION THREAD

**Discussion by tcurdt** [grafana-cold-storage/agent#2670] [Q&A] [answered]
I want to have labels on the metrics from the discovery:

        - job_name: integrations/nodejs
          metrics_path: /api/metrics
          consul_sd_configs:
          - server: '127.0.0.1:8500'
            services:
              - 'backend-production'
              - 'backend-staging'
          # metric_relabel_configs:

I could not find an example or docs on how to match inside Grafana which service the metrics were coming from ('backend-production' or 'backend-staging')
 

I want the data coming from the "backend-production" service to also have a label added clarifying it is coming from a backend-production service.

The instance label has the host and port - but I also need the service label.
Unfortunately I have not found any information in the docs on how to do that when the discovery is dynamic.

Right now I am getting for example:

    backend_foo{instance="10.0.1.2:22026"}
    backend_foo{instance="10.0.1.2:22023"}

But what I want is

    backend_foo{instance="10.0.1.2:22026", service="backend-production"}
    backend_foo{instance="10.0.1.2:22023", service="backend-staging"}

I don't see how to write the relabel_configs/metric_relabel_config to reference the service.

**Comment by rfratto** [comment]
The Prometheus [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config) says that `__meta_consul_service` is the meta label containing the service name that you can use for relabeling.   

```yaml
relabel_configs:
- source_labels: ['__meta_consul_service'] 
  target_label: service 
```

**Reply by tcurdt** [reply]
Thanks! I will give that a try.

I was a bit lost on where to place the relabel config.

**Reply by tcurdt** [reply]
Should it be `relabel_configs` or `metrics_relabel_configs`?

```
        - job_name: integrations/nodejs
          metrics_path: /api/metrics
          consul_sd_configs:
          - server: '127.0.0.1:8500'
            services:
              - 'backend-production'
              - 'backend-staging'
          # metric_relabel_configs:
          relabel_configs:
          - source_labels: ['__meta_consul_service'] 
            target_label: service 

```

Is there a schema for current version of the yml?
