### DISCUSSION TITLE
integrations & integrations revamp compatibility

### DISCUSSION THREAD

**Discussion by aglees** [grafana-cold-storage/agent#3468] [Q&A]
Is it possible to run integrations & integrations revamp inside the same pod? I gave it a quick go with CloudWatch Exporter (legacy) and EventHandler (revamp), and it didn't seems want to run. 

Is there a definitive answer on this?

**Comment by tpaschalis** [comment]
The `--enable-features=integrations-next` feature flag enables some _new_ integrations but also has support for _all_ the previous ones.

You might have to tinker with your configuration a little bit as detailed [here](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/#config-changes), but you'll be able to make use of both of them!

If you can't figure out what to change in the configuration, feel free to post the error you're getting along with your config file after removing any sensitive information.

**Comment by buckleyGI** [comment]
I have tried many iterations of the agent config but none of them work :( I also went through the documentation that mentions some renames/breaking changes. Can you please help 🙏 Me and my teammate have spent a few days on it :(

We are trying to setup the redis integration from our EKS kubernetes to Grafana Cloud using the static yaml method, so not the operator if that makes a difference.

Thank you!!

```
    integrations:
      redis_configs:
          - redis:
              enabled: true
              redis_addr: "redis-2:6379"
              relabel_configs:
              - source_labels: ""
                target_label: instance
                replacement: redis-2

      eventhandler:
        cache_path: /var/lib/agent/eventhandler.cache
        logs_instance: integrations
    logs:
```

And we get

```
2023/06/16 14:51:49 error loading config file /etc/agent/agent.yaml: yaml: unmarshal errors:
  line 1: field redis not found
```
