### DISCUSSION TITLE
Metrics not showing up from cert-manager and traefik

### DISCUSSION THREAD

**Discussion by Drabuna** [grafana-cold-storage/agent#375] [Q&A] [answered]
Hi!

I followed the quick start guide to setup Grafana Cloud Agent on a Kubernetes cluster (running on Digital Ocean).
First, I generated YAML files using the deployment shell scripts, and then I applied them.
I can see metrics and logs in my Grafana UI.

I also have `traefik` and `cert-manager` running in my cluster.
I can see logs from both `traefik` and `cert-manager`.
When exploring `up` metrics in the UI, I can see instances of `traefik`, but not `cert-manager`.
When I port-forward, I can see `/metrics` displaying data for both of them.

Here's how I configured scraping in the agent:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: infra
---
apiVersion: v1
data:
  agent.yml: |
    prometheus:
        configs:
          - name: integrations
            scrape_configs:
              - job_name: cert-integration
                static_configs:
                  - targets: ['cert-manager:9402']
              - job_name: traefik-integration
                static_configs:
                  - target: ['traefik:9090']
          - host_filter: true
            name: agent
#... the rest of standard template      
```
Agent, traefik and cert-manager are in the same namespace (if that matters).
After applying, I did rolling restart of both `deployment/grafana-agent-deployment` and `daemonset/grafana-agent`

Metrics won't show up :(

Help would be greatly appreciated :)
