### DISCUSSION TITLE
Historical Data won't be scraped by agent with honor_timestamps set to true

### DISCUSSION THREAD

**Discussion by azadsagar** [grafana-cold-storage/agent#4113] [Q&A]
Our metrics are exposed on /metrics endpoint. Exposed metrics dumps it's own timestamp. This time stamp is older by one hour. I don't
eg: if current time is 17:33, actual timestamp on the exposed endpoint is 16:33 for given set of metrics.

```
aws_alb_consumed_lcus_sum 0.0002888888888888889 1686308760000
```

My agent config looks as below:
```
metrics:
  wal_directory: /tmp/wal
  global:
    remote_write:
      - url: http://localhost:9090/api/v1/write
  configs:
    - name: default
      scrape_configs:
        - job_name: agent
          metrics_path: /metrics
          scrape_interval: 1m
          honor_timestamps: true
          honor_labels: true
          static_configs:
            - targets: ['localhost:8080']
integrations:
  agent:
    enabled: true
```

Even with the honor_timestamps set to true (which is default as per the prometheus document), agent won't scrape or push these metrics.
