### DISCUSSION TITLE
Flow/River: How do I set tenant ID for traces dynamically based on the trace attributes? How do I set trace attributes?

### DISCUSSION THREAD

**Discussion by fawadasaurus** [grafana-cold-storage/agent#4774] [Q&A]
I had this agent config before river and it works.
```yaml
    traces:
        configs:
            - name: kubernetes-traces
              receivers:
                otlp:
                    protocols:
                        grpc: null
              remote_write:
                - endpoint: tempo-gateway.platform-o11y.svc.cluster.local:81
                  headers:
                    x-scope-orgid: myco
                  insecure: true
                  retry_on_failure:
                    enabled: true
                  protocol: grpc
                  format: otlp
                  compression: none
              scrape_configs:
                - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                  job_name: kubernetes-pods
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_namespace
                      target_label: namespace
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_name
                      target_label: pod
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_container_name
                      target_label: container
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_label_tenant
                      target_label: tenant_id
                  tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: true
```

From what I understand, I can not dynamically set the `x-scope-orgid` with `tenant_id` in the old config syntax but I should be able to in river?

Here is my current river file.  where I am stuck is that I have no idea what a `context` is. Where can I set the value for `tenant_id` so that it can be used in `from_context`?
```
    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }

      output {
        traces  = [otelcol.exporter.otlp.default.input]
      }
    }

    otelcol.auth.headers "creds" {
      header {
        key          = "X-Scope-OrgID"
        from_context = "tenant_id"
      }
    }

    otelcol.exporter.otlp "default" {
      client {
        endpoint = "tempo-gateway.platform-o11y.svc.cluster.local:81"
        tls {
          insecure = true
        }
        auth = otelcol.auth.headers.creds.handler
      }
    }
```
