### DISCUSSION TITLE
how-to-use-envs-in-static-agent-configmap

### DISCUSSION THREAD

**Discussion by TomasHradecky** [grafana-cold-storage/agent#5173] [Q&A]
Hello,
could you please help me how to use env in configmap for grafana-agent in static mode ?
I would like to get password for remote_write from env so I’ve enabled -config.expand-env through values.agent.extraArgs,
env is defined by
```
extraEnv:
      - name: REMOTE_WRITE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: grafana-agent-remote-write
            key: password
```
and specification of configmap content by
```
   configMap:
      content: |-
        metrics:
          configs:
              remote_write:
                - url: https://myprometheus/prometheus/api/v1/write
                  basic_auth:
                    password: ${REMOTE_WRITE_PASSWORD}
                    username: username
```
Unfortunately env is not expanded. Any idea what is the issue ?
