### DISCUSSION TITLE
how to add x-scope-orgid in log instance file of grafana operator crd

### DISCUSSION THREAD

**Discussion by aryan-brane-1971** [grafana-cold-storage/agent#5470] [Q&A]
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: primary
  namespace: observability
  labels:
    agent: grafana-agent-logs
spec:
  clients:
  - url: https://loki.nslhub.click/api/prom/push
    externalLabels:
      cluster: cloud
      app: operator-crd

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the LogsInstance CR
  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels:
      instance: primary

**Comment by stewartshea** [comment]
Judging my the CRD here, this is in the form of `tenantId` 

https://grafana.com/docs/agent/latest/operator/api/#monitoring.grafana.com/v1alpha1.LogsClientSpec

This is the default spec that the loki `self-monitoring` tenant uses: 
```
  spec:
    clients:
    - externalLabels:
        cluster: loki
      tenantId: self-monitoring
      url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
```
