### DISCUSSION TITLE
Drop kubernetes node labels

### DISCUSSION THREAD

**Discussion by UbiquitousBear** [grafana-cold-storage/agent#5790] [Q&A] [answered]
Hey, I'm trying to drop kubernetes node labels from being sent upstream, however, I'm unsure what to use as the source. I've tried using `__name__` however this is not effective. I assume `__name__` is incorrect as that applies to the metric name, so what am I meant to be using?

```
relabel_configs:
 - source_labels: [__name__]
    regex: (.+)kubevirt(.+)
    action: drop
```

The K8s node itself has labels such as: `kubevirt.io/schedulable=true` which I'm trying to filter out, where the label contains the word `kubevirt`.
