### DISCUSSION TITLE
What would you like to see in the Grafana Agent?

### DISCUSSION THREAD

**Discussion by rfratto** [grafana-cold-storage/agent#593] [Ideas]
Hi everyone! 

I'd like to collect feedback from the community for how we can improve the Grafana Agent. The goal is to help us determine what areas need attention or what we can add to improve the Agent.  

All feedback is welcome here! Do you have a feature request you're *dying* to see? Or maybe a pain point that drives you a little crazy? Please share! 

If you see a comment from another user you agree with, vote it up! This will help us get a sense of how popular a comment is, which can help with prioritizing.

**Comment by BitProcessor** [comment]
It would be really nice if grafana agent would be able to add the container image + tag as label to the logs. 

This can be helpful when debugging logs during an automatic (or even manual) deploy of a new container image on kubernetes. 
Or even to see if logs are still coming from a old version of the image that is supposed to be long gone etc...

**Comment by verygoodsoftwarenotvirus** [comment]
I want to give an up-front disclaimer to this wall of text that I have great appreciation, respect, and gratitude for Grafana, Grafana Cloud, the Agent, and everybody who works on it. Any requests or suggestions I make here are meant to be humble requests, not vigorous demands. :)

### Configuration

The by-and-large impression I get from the Agent documentation is that it is primarily designed to be run either as a sidecar in a Kubernetes pod, or as a daemon on a box. In my case, I'm deploying to Amazon ECS, so a lot of the available documentation has to be taken with a fair amount of salt. 

For instance, configuring the agent requires changing the command to point to the relevant config file, but in ECS the only real way to mount such a volume would be to build a one-off container that inherits from the Grafana-provided agent image. So I'd have to have something like:

```
FROM grafana/agent:v0.21.2

ADD ./configs/agent-config.yaml /etc/agent/agent.yaml
```

then build and push that image to ECR and use it as the sidecar. I know there is a [remote configuration option](https://grafana.com/docs/agent/latest/configuration/#remote-configuration-beta) in beta, but a better option for me, IMO, is what [the AWS OTel Collector does](https://aws-otel.github.io/docs/setup/ecs/config-through-ssm/): allow me to set an environment variable with an SSM Parameter name, and fetch the config from there. This way, I don't have to worry about securing an HTTP route serving a configuration file, because everything is kept within AWS proper.

If I'm allowed to make wishes, a complete start-to-finish guide for using Grafana Agent in ECS/Fargate would be incredible. :)

### Debugging

My recent goal was to use Grafana Cloud to monitor my ECS service by using the Grafana Agent as a sidecar. To validate that I had set up my configuration file correctly, I ran the [example docker-compose instance](https://github.com/grafana/agent/tree/21fb297708d60d0252d727f12b1b9e82db8ba8f6/example/docker-compose), only I made the relevant changes to the config file that I had assumed would yield logs/metrics/traces in Grafana Cloud. The only thing I was able to get working was [logs](https://twitter.com/vgsnv/status/1471680784260112386/photo/1), but the Agent didn't log or note any particular reason why. The only file I changed was [this one](https://github.com/grafana/agent/blob/21fb297708d60d0252d727f12b1b9e82db8ba8f6/example/docker-compose/agent/config/agent.yaml). 

I guess I'd issue a minor challenge to whoever reads this if you're up for it: do what I did. Set up a Stack in Grafana Cloud, and use the provided configuration details to get the local load test stuff working. If you can do it, I'd really really really love some details as to what I did wrong (which I acknowledge is hard to ascertain without seeing my configs). I'll try to reproduce and add supplementary evidence to this portion once I'm back at my personal machine.

I reserve the right to blab more in here later as I think of things. :)

**Reply by rfratto** [reply]
Hey! Thanks for taking the time to write all of this, I really appreciate it and we'll make sure we go through several reads of this to get all the takeaways. 

> The by-and-large impression I get from the Agent documentation is that it is primarily designed to be run either as a sidecar in a Kubernetes pod, or as a daemon on a box. In my case, I'm deploying to Amazon ECS, so a lot of the available documentation has to be taken with a fair amount of salt.

I'm surprised you get that impression. The sidecar model is actually _not_ recommended due to the performance overhead of running many agents. This tells me we need to be more clear about this in the documentation.

The deployment model of the agent is complicated thanks to using a WAL and Kubernetes not supporting PVCs for DaemonSets, but quickly breaking it down:

1. If you're not using Kubernetes, you can run one agent per machine. 
2. If you _are_ using Kubernetes, then you need to combine an agent DaemonSet (for logs only), and an agent StatefulSet for metrics. Traces doesn't have a strict requirement and can be deployed through any controller. This is something we're deeply aware of being a PITA and we're planning on investing in the operator to remove this operational burden. 

> a better option for me, IMO, is what the AWS OTel Collector does: allow me to set an environment variable with an SSM Parameter name

Would https://github.com/grafana/agent/issues/926 be what you're looking for here? 

> If I'm allowed to make wishes, a complete start-to-finish guide for using Grafana Agent in ECS/Fargate would be incredible. :)

Absolutely. Knowing how to use the agent to collect telemetry from ECS/Fargate is our weakest point right now, given the deployment constraints I mentioned earlier. My understanding is that it's particularly difficult to collect logs. I agree that we need to invest more effort into documenting and supporting it.  

> If you can do it, I'd really really really love some details as to what I did wrong (which I acknowledge is hard to ascertain without seeing my configs). 

I'd definitely like to see the configs (with secrets removed, of course) that haven't worked for you. Debugging metrics can be a pain, and we haven't yet documented how to do it. One example of a pain point was brought up today here: https://github.com/grafana/agent/issues/1188

I'll be on the lookout for more feedback from you :) Our documentation hasn't been getting a lot of love, which I imagine is really frustrating from people who are starting fresh and aren't migrating from Prometheus+Promtail+OTel-collector. It's something I definitely want us to improve alongside debug tooling to make it easier to track down config problems.

**Reply by verygoodsoftwarenotvirus** [reply]
> I'm surprised you get that impression. The sidecar model is actually not recommended due to the performance overhead of running many agents. This tells me we need to be more clear about this in the documentation.

I think the thoroughness of of [the Grafana Agent Operatior section of the docs page](https://grafana.com/docs/agent/latest/operator/) is probably what lead me to this conclusion, in hindsight, but yeah, I totally conflated operators and sidecars there, my bad! :sweat_smile: 

> Would #926 be what you're looking for here?

I could see that working, minified JSON would be valid to put in an env var, and would parse as YAML just fine.

> My understanding is that it's particularly difficult to collect logs. I agree that we need to invest more effort into documenting and supporting it.

There is [existing documentation on getting logs into Grafana Cloud via Firelens](https://grafana.com/blog/2020/08/06/loki-tutorial-how-to-send-logs-from-amazons-ecs-to-loki/), that I was able to deploy successfully. I didn't pay this too much attention because IIRC the status of logging in the OTel collector spec is still experimental. 

> I'd definitely like to see the configs (with secrets removed, of course) that haven't worked for you. Debugging metrics can be a pain, and we haven't yet documented how to do it. One example of a pain point was brought up today here: #1188

I'll spin this all up again in a few hours and post a reply to this thread with the best that I can do. I 1000% anticipate my problems are user error on my part. :)

**Reply by verygoodsoftwarenotvirus** [reply]
Sorry I am so late to update this. I do think the matter of not being able to send things to Grafana Cloud from the example as I had described ended up being user error on my part. Thank you for your patience with me in all of this. :) Previously I couldn't get anything but logs to show up. After some fiddling, I am able to get metrics and logs to show up, but I did also realize I was querying for metrics incorrectly. I'm able to view logs by querying for ``, and metrics by querying for ``, but I can't seem to find a working query that yields traces (``, for instance, yields nothing). That said, but I'm more confident than ever it's because I don't understand querying as well as I thought. :upside_down_face:  Here's my config, sans secrets:

```yaml
server:
  log_level: debug
  http_listen_port: 12345

metrics:
  global:
    scrape_interval: 1m
  configs:
    - name: test
      host_filter: false
      scrape_configs:
        - job_name: crow
          static_configs:
            - targets: ['crow:8080']
              labels:
                cluster: 'docker_compose'
                container: 'crow'
                pod: 'crow'
        - job_name: crow_validate
          metrics_path: /validate
          static_configs:
            - targets: ['crow:8080']

        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345', '127.0.0.1:8889']
              labels:
                cluster: 'docker_compose'
                container: 'agent'
                pod: 'grafana-agent-local'
        - job_name: cortex_scrape
          static_configs:
            - targets: ['cortex:9009']
              labels:
                cluster: 'docker_compose'
                container: 'cortex'

        - job_name: avalanche-1
          static_configs:
            - targets: ['avalanche-1:9001']
              labels:
                cluster: 'docker_compose'
                container: 'avalanche-1'
        - job_name: avalanche-2
          static_configs:
            - targets: ['avalanche-2:9001']
              labels:
                cluster: 'docker_compose'
                container: 'avalanche-2'
        - job_name: avalanche-3
          static_configs:
            - targets: ['avalanche-3:9001']
              labels:
                cluster: 'docker_compose'
                container: 'avalanche-3'
      remote_write:
        - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
          basic_auth:
            username: <relevant_username>
            password: <relevant_password>

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://<relevant_username>:<relevant_password>@logs-prod-us-central1.grafana.net/loki/api/v1/push
    scrape_configs:
    - job_name: system
      static_configs:
        - targets:
          - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log

traces:
  configs:
    - name: default
      receivers:
        jaeger:
          protocols:
            thrift_http:
      attributes:
        actions:
          - action: upsert
            key: env
            value: prod
      remote_write:
        - endpoint: tempo-us-central1.grafana.net:443
          basic_auth:
            username: <relevant_username>
            password: <relevant_password>
      batch:
        timeout: 5s
        send_batch_size: 100
      automatic_logging:
        backend: logs_instance
        logs_instance_name: default
        spans: true
        processes: true
        roots: true
      spanmetrics:
        handler_endpoint: 0.0.0.0:8889
      service_graphs:
        enabled: true
```
