### DISCUSSION TITLE
x-faro-session-id header for faro receiver giving CORS error

### DISCUSSION THREAD

**Discussion by navya-zs** [grafana-cold-storage/agent#6041] [Q&A]
Hi ,
I am using grafana agent to monitor the logs but facing the below error while I am initialising faro

Access to fetch at 'http://localhost:12345/collect' from origin 'http://localhost:8000/’ has been blocked by CORS policy: Request header field x-faro-session-id is not allowed by Access-Control-Allow-Headers in preflight response.

Steps to reproduce
- Run latest version of Grafana Agent
- Run latest version of Grafana Faro Web SDK

Latest release v0.38.1 says,
Bugfixes: 
Permit X-Faro-Session-ID header in CORS requests for the faro.receiver
       component (flow mode) and the app_agent_receiver integration (static mode).
       
Though I have upgraded the agent version to v0.38.1 and restarted the agent I am still facing the same error

Currently I am using, 

grafana-agent static mode
faro-web-sdk version: v1.3.5
Grafana-agent version: v0.38.1

Any idea what is the issue ? What am I missing?

**Comment by rfratto** [comment]
Can you share your config?

**Reply by navya-zs** [reply]
This is my grafana agent config

```yaml
server:
  log_level: debug
metrics:
  wal_directory: /tmp/wal
  global: {}
  configs:
    - name: default
      remote_write:
        - url: http://localhost:5001/api/v1/push
          headers:
            x-org-api-key: 8c2b26fd-5e8e-4cb6-816d-25999ce3543e
logs:
  positions_directory: /tmp/loki-pos
  configs:
    - name: default
      clients:
        - url: http://localhost:8000/farologs
          tenant_id: 8c2b26fd-5e8e-4cb6-816d-25999ce3543e
traces:
  configs:
    - name: default
      batch:
      receivers:
        otlp:
          protocols:
            grpc: 
      remote_write:
        - endpoint: localhost:55680
          insecure: true
integrations:
  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      instance: 'frontend'
      logs_instance: 'default'
      server:
        host: 0.0.0.0
        port: 12345
        cors_allowed_origins: 
          - '*'
      logs_labels: 
        app: frontend 
        kind: # value will be taken from log items. exception, log, measurement, etc
        page_url:
        app_name:
      logs_send_timeout: 5000
      sourcemaps:
        download: true
```
