### DISCUSSION TITLE
Grafana Agent Integrations

### DISCUSSION THREAD

**Discussion by SanthoshKumar18245** [grafana-cold-storage/agent#6387] [Q&A] [answered]
Hi ,
I am having a problem with the grafana-agent .. the thing is i have configured the agent to scrape the metrics from ubuntu instance but it shows me like some file are missing and some are being Ignored

![image](https://github.com/grafana/agent/assets/133011171/cb134289-06d5-4ac7-a2b3-b531ca38f1a7)

here is my yaml file..

```
server:
  log_level: debug

metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://localhost:9009/api/v1/push
        headers:
          X-Scope-OrgID: windows_monitoring
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    disable_collectors:
      - "mdadm"
```

grafana team answer me about this ?
@bcotton @torkelo @jpkrohling @darxriggs
