### DISCUSSION TITLE
How to setup authentication for writing data to grafana agent flow mode on kubernetes

### DISCUSSION THREAD

**Discussion by srinivasmummareddy** [grafana-cold-storage/agent#6472] [Q&A]
I'm trying to authenticate the user before accepting data to grafana-agent based on bearer token. Is there any similar thing like following code  of Otelcollector?

```
Otel-collector
receivers:
  otlp/secure:
    protocols:
      http:
        auth:
          authenticator: oidc/server
```
          
    Grafana-agent:
      otelcol.receiver.otlp "example" {
        grpc {}
        http {}
        output {
          metrics = [otelcol.processor.batch.example.input]
          logs    = [otelcol.processor.attributes.customlabelsd.input]
          traces  = [otelcol.processor.batch.example.input]
        }
      }
     
     
     I couldn't find much w.r.t receivers authentication but saw some token generation for oauth w.r,t exporters...
