### DISCUSSION TITLE
Node exporter and kube state metrics missing

### DISCUSSION THREAD

**Discussion by cloudcafetech** [grafana-cold-storage/agent#650] [Q&A]
Installed using https://github.com/grafana/agent#getting-started ...

But missing node exporter and kube state metrics.

Do I need to anything more ?

**Comment by rfratto** [comment]
Hi! The Kubernetes install scripts [just look for pods to collect metrics from](https://github.com/grafana/agent/blob/main/docs/getting-started.md#kubernetes-install-script). You'll need to install node_exporter and kube-state-metrics on your cluster and make sure they conform to the rules from the link I shared for them to be picked up.

**Comment by cloudcafetech** [comment]
@rfratto 

Thanks, forgot to deploy those pods. It's working now.👍

Another couple of questions , 

Does trace agent discover automatically? 
How to set external labels?

Please help me to get tracing sample hotrod application.

Thanks in advance.

**Reply by mapno** [reply]
Hi!

> Does trace agent discover automatically?

The Grafana Agent does not discover tracing targets. It's push-based.

> How to set external labels?

Ideally, you make make use of `scrape_configs `. An alternative is using the attributes processor. See [pipeline processing](https://grafana.com/docs/tempo/latest/grafana-agent/#pipeline-processing).

> Please help me to get tracing sample hotrod application.

I assume you're referring Jaeger's [Hot R.O.D.](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod) example. To make that application work with the Grafana Agent you will need two things:

1. Run the Grafana Agent with Jaeger receivers: see [receiver block](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#tempo_config).
2. Point the Jaeger Agent [config](https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/docker-compose.yml#L15) to you Grafana Agent's address

**Comment by cloudcafetech** [comment]
Something like below,

```
           receivers:
                jaeger:
                    protocols:
                        grpc: null
                        thrift_binary: null
                        thrift_compact: null
                        thrift_http: null
                    remote_sampling:
                        insecure: true
                        strategy_file: /etc/agent/strategies.json
                opencensus: null
                otlp:
                    protocols:
                        grpc: null
                        http: null
                zipkin: null
```

Is there any value for null? or keep as it is.
